remove_low_conf:
  min_detect_score: 0.0
  max_height: 300
  min_height: 0

bbox2point:
  bbox_to_point_ratio: 0.1

inpolygon:
  area_num: 1
  area_point_len: [4,0,0,0]
  area_point: [
                [[250,50],[250,250],[50,250],[50,50],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0]],
                [[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0]],
                [[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0]],
                [[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0]]
              ]

stabilizer:
  iir_up_ratio: 0
  iir_down_ratio: 0
