remove_low_conf:
  min_detect_score: 0.0
  max_height: 1080
  min_height: 0

bbox2point:
  bbox_to_point_ratio: 1.0

inpolygon:
  area_num: 2
  area_point_len: [4,4,0,0]
  area_point: [
                [[520,1079],[735,630],[1445,630],[1870,1079]],
                [[740,615],[805,467],[1300,467],[1440,615]],
                [[520,1079],[805,467],[1290,467],[1683,1079]],
                [[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0]],
                [[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0]]
              ]

stabilizer:
  iir_up_ratio: 0.2
  iir_down_ratio: 0.9
